#!/bin/sh

### BEGIN INIT INFO
# Provides:          blackmon
# Required-Start:
# Required-Stop:
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Dell Inspiron BlackMon fan tool
### END INIT INFO

# blackmon	Dell Inspiron BlackMon fan tool monitor
#
#		Written by Daniel Stavrovski <d@stavrovski.net>.
#
# => /etc/default/blackmon 
## set to 1 to enable blackmon
##ENABLED=1

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

NAME=blackmon
USER=d
DAEMON=/home/d/bin/blackmon-project/blackmon
PROC_I8K=/proc/i8k
DESC="Dell Inspiron BlackMon fan tool"
ENABLED=0

test -x $DAEMON || exit 5

if [ -f /etc/default/$NAME ] ; then
	. /etc/default/$NAME
fi
if [ ! -f /var/run/$NAME.pid ] ; then
	touch /var/run/$NAME.pid
	chown $USER:$USER /var/run/$NAME.pid
fi
case "$1" in
	start)
		if [ "$ENABLED" = 0 ]; then
			log_warning_msg "Not starting. Disabled via /etc/default/$NAME "
			exit 0
		fi
		log_daemon_msg "Starting $DESC" "$NAME "
		modprobe i8k >/dev/null 2>&1 || true
		if [ ! -f "$PROC_I8K" ]; then
			log_progress_msg "Could not find $PROC_I8K."
			log_end_msg 1
			exit 1
		fi
		start-stop-daemon --start --oknodo --user $USER --name $NAME \
                   --startas $DAEMON \
                   --chuid $USER -- --daemon
		log_end_msg $?
		;;
	stop)
		log_daemon_msg "Stopping $DESC" "$NAME "
		start-stop-daemon --oknodo --stop --quiet --name $NAME
		log_end_msg $?
		;;
	status)
    	status_of_proc $DAEMON $NAME && exit 0 || exit $?
    	;;
	*)
		echo "Usage: $0 {start|stop|status}" >&2
		exit 2
		;;
esac